// These styles apply to every route in the application
import "@/styles/globals.css";
import { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";

import { headers } from "next/headers";

import { TRPCReactProvider } from "@/../trpc/react";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});


export const metadata: Metadata = {
   title: "Create T3 App",
  description: "Generated by create-t3-app",
  twitter: {
    card: "summary_large_image",
      title: "Create T3 App",
  description: "Generated by create-t3-app",
  },
  metadataBase: new URL("https://nextjs-postgres-auth.vercel.app"),
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <Toaster />
        <TRPCReactProvider headers={headers()}>{children}</TRPCReactProvider>
        
      </body>
    </html>
  );
}
